use_frameworks!

platform :ios, '9.0'

target 'GQAFRequestTool_Example' do
  pod 'AFNetworking', '~> 4.0.1'
  pod 'GQAFRequestTool', :path => '../'

  target 'GQAFRequestTool_Tests' do
    inherit! :search_paths

    
  end
end
